### ISSUE TITLE
 задавать вопросы 

### ISSUE THREAD

**Issue by chtys2008** [deniro98/s330fn#2]
Здравствуйте, друзья, я из китая.  Извините, что беспокою вас, мой компьютер модели также S3 S330, но я 330 UN, после использования вашей EFI, не может войти в систему, а затем удалите dsdt.aml после того, как вы можете войти, но синий зуб не может драйвер. 
 скажите, пожалуйста, где Ваша почта?  можно связаться с вами?

**Comment by chtys2008** [comment]
Hello friend, I'm from China. I'm sorry to disturb you. My computer model is also S3 S330, but my model is 330un. After using your EFI, I can't access the system. After deleting dsdt.aml, I can access it. But Bluetooth can't drive it.

Can I get in touch with you? My email is chtys2008@gmail.com, thank you very much!

**Comment by deniro98** [comment]
Can you send your config.plst and kexts directory screenshot?

**Comment by deniro98** [comment]
I had such a problem a couple of times, it worked after I put the bluetooth kext  in L/E, after that dont forget  rebuild kext caches.

**Comment by chtys2008** [comment]
OK, thank you for your reply. These are my configuration pictures. All the files are shared by you. After deleting CLOVER\ACPI\patched\DSDT.aml , i can enter the system, but Bluetooth and the network cannot be driven.
What kind of IM do you use? Like wechat? Or email, I can contact you. It doesn't seem to share pictures.

**Comment by chtys2008** [comment]
Sorry, I seem to have made a mistake. Did I delete this conversation?

**Comment by chtys2008** [comment]
Sorry, I seem to have made a mistake. Did I delete this conversation? I found your twitter and Facebook on your website, please allow me to add you, OK?

**Comment by deniro98** [comment]
No, send here names of kext directory,  and try to put bluetooth''s kext to L/E
