### ISSUE TITLE
Clover problem

### ISSUE THREAD

**Issue by Toxicccxz** [deniro98/s330fn#3]
Hi bro, it's soooo good that finally find some one use the same laptop as mine. Great work tho
I was trying install MacOs into it with your EFI(I just delete all files under EFI folder and put all your files into it, not only the ‘BOOT’ and ‘CLOVER’), but the problem is first time it can get into CLOVER let me select how to install and everything went well, but after that I never can get into CLOVER again, each time the MacOs's recovery mode shows up and let me reinstall it (but when i select reinstall it wont continue because it need network).
do you know what happened?

**Comment by Toxicccxz** [comment]
Oh  I didn't move clover efi to the disk
the problem is sloved, thx a lot, this is a really perfect hackintosh!

**Comment by deniro98** [comment]
@Toxicccxz Have you HDMI works?
